name: Aggiorna Fonte Azzurra

on:
  schedule:
    - cron: '0 */6 * * *'  # ogni 6 ore
  workflow_dispatch:

jobs:
  update-main:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3️⃣ Installa dipendenze necessarie
      - name: Install dependencies
        run: |
          set -e
          python -m pip install --upgrade pip
          pip install feedparser beautifulsoup4 requests

      # 4️⃣ Esegui aggregator.py
      - name: Esegui aggregator.py
        run: python aggregator.py

      # 5️⃣ Verifica PAT_TOKEN
      - name: Verifica PAT_TOKEN
        run: |
          set -e
          if [ -z "${{ secrets.PAT_TOKEN }}" ]; then
            echo "ERRORE: PAT_TOKEN non t_
