name: Aggiorna Fonte Azzurra

on:
  schedule:
    - cron: '0 */6 * * *' # ogni 6 ore
  workflow_dispatch:

jobs:
  build-and-pr:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: pip install feedparser

      # 4️⃣ Esegui aggregator.py
      - name: Esegui aggregator.py
        run: python aggregator.py

      # 5️⃣ Commit e push su branch temporaneo usando PAT
      - name: Commit e push su branch aggiornamento-articoli
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.co
