name: Aggiorna Fonte Azzurra

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: pip install feedparser

      # Esegui aggregator.py
      - name: Run aggregator
        run: python aggregator.py

      # Commit e push con PAT
      - name: Commit and push with PAT
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "action"
