name: Aggiorna Fonte Azzurra

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          set -e
          python -m pip install --upgrade pip
          pip install feedparser beautifulsoup4 requests

      - name: Esegui aggregator.py
        run: |
          set -e
          python aggregator.py

      - name: Verifica PAT_TOKEN
        run: |
          set -e
          if [ -z "${{ secrets.PAT_TOKEN }}" ]; then
            echo "ERRORE: PAT_TOKEN non trovato!"
            exit 1
          else
            echo "PAT_TOKEN presente, pronto per il push."
          fi

      - name: Commit e push su main
        run: |
          set -e
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git fetch origin main
          git checkout main
          git add index.html feed.json

          if git diff --cached --quiet; then
            echo "Nessuna modifica da committare"
          else
            git commit -m 'Aggiornamento automatico articoli'
            git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/thebrave27/fonte-azzurra.git main
