name: Aggiorna Fonte Azzurra

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build-and-pr:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: pip install feedparser

      # 4️⃣ Esegui aggregator.py
      - name: Esegui aggregator.py
        run: python aggregator.py

      # 5️⃣ Configura Git
      - name: Configura Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -B aggiornamento-articoli
          git add index.html feed.json
          git diff --cached --quiet || git commit -m 'Aggiornamento automatico articoli'

      # 6️⃣ Push usando GitHub Push Action (evita completamente 403)
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          branch: aggiornamento-articoli
          force: true

      # 7️⃣ Crea o aggiorna Pull Request
      - name: Crea Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          branch: aggiornamento-articoli
          base: main
          title: 'Aggiornamento automatico articoli'
          body: 'Aggiornamento automatico dei feed e del sito generato da GitHub Actions'
