name: Aggiorna Fonte Azzurra

on:
  schedule:
    - cron: '0 */6 * * *' # ogni 6 ore
  workflow_dispatch:

jobs:
  update-main:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: pip install feedparser

      # 4️⃣ Esegui aggregator.py
      - name: Esegui aggregator.py
        run: python aggregator.py

      # 5️⃣ Verifica PAT_TOKEN
      - name: Verifica PAT_TOKEN
        run: |
          if [ -z "${{ secrets.PAT_TOKEN }}" ]; then
            echo "ERRORE: PAT_TOKEN non trovato!"
            exit 1
          else
            echo "PAT_TOKEN presente, pronto per il push."
          fi

      # 6️⃣ Commit e push su main solo se ci sono modifiche
      - name: Commit e push su main
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git checkout main
          git add index.html feed.json

          # Controlla se ci sono modifiche
          if git diff --cached --quiet; then
            echo "Nessuna modifica da committare"
          else
            git commit -m 'Aggiornamento automatico articoli'
            # Push usando il PAT direttamente nell'URL
            git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/thebrave27/fonte-azzurra.git main
          fi
