name: Aggiorna Fonte Azzurra

on:
  schedule:
    - cron: '0 */6 * * *' # ogni 6 ore
  workflow_dispatch:

jobs:
  build-and-pr:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: pip install feedparser

      # 4️⃣ Esegui aggregator.py
      - name: Esegui aggregator.py
        run: python aggregator.py

      # 5️⃣ Configura Git, commit e push usando PAT
      - name: Commit e push su branch aggiornamento-articoli
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Crea o passa al branch temporaneo
          git checkout -b aggiornamento-articoli || git checkout aggiornamento-articoli

          # Aggiunge i file modificati
          git add index.html feed.json

          # Commette solo se ci sono cambiamenti
          git diff --cached --quiet || git commit -m "Aggiornamento automatico articoli"

          # Push del branch usando il PAT salvato come secret
          git push --set-upstream https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/thebrave27/fonte-azzurra.git aggiornamento-articoli

      # 6️⃣ Crea una Pull Request verso main
      - name: Crea Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          branch: aggiornamento-articoli
          base: main
          title: "Aggiornamento automatico articoli"
          body: "Aggiornamento automatico dei feed e del sito generato da GitHub Actions"
